import random
import re

# Enhanced fun facts for the original 151 Pokémon
ORIGINAL_151_FACTS = {
    "Bulbasaur": "Bulbasaur cultivates ancient olive trees in Olympia, home of the first Olympic Games. Recently, it started a viral TikTok trend where it uses Vine Whip to create perfect frappé foam in Athenian cafés!",
    "Ivysaur": "Ivysaur's flowering back inspired Corinthian columns in Greek architecture. It now runs a popular flower shop in Mykonos, specializing in bouquets that change color at sunset.",
    "Venusaur": "Venusaur provides shade for philosophers in the Athenian Agora. During the 2004 Olympics, it temporarily became the official mascot but was disqualified for accidentally crushing the shot put field.",
    "Charmander": "Charmander lights the eternal flame at Zeus' altar in Olympia. It moonlights as a souvlaki grill master, though it constantly has to apologize for overcooking orders.",
    "Charmeleon": "Charmeleon warms thermal baths at Thermopylae. It recently caused panic at a Santorini winery when it tried to speed-age wine by breathing on the barrels.",
    "Charizard": "Charizard once tried to roast a whole lamb for Easter but accidentally created souvlaki! Now it stars in a reality TV show called 'Dragon Kitchen Nightmares' where it fixes struggling Greek tavernas.",
    "Squirtle": "Squirtle helps extinguish forest fires during Greek summers. It's currently training for the national water polo team but keeps getting penalized for using Withdraw during matches.",
    "Wartortle": "Wartortle patrols Corfu's canals keeping them clean. Locals swear it's the reincarnation of an old sea captain who disappeared in the 1950s during a freak storm.",
    "Blastoise": "Blastoise creates water shows at the Poseidon Temple. Its latest stunt involved hydro-pumping a perfect rainbow over the Acropolis that lasted 3 hours, breaking all Instagram records.",
    "Caterpie": "Caterpie spins silk for traditional Greek wedding dresses. It caused chaos at a fashion show when it evolved mid-catwalk and ate half the collection.",
    "Metapod": "Metapod's shell inspired ancient Greek shield designs. It now runs a meditation retreat on Mount Athos where tourists pay to 'find their inner hardness'.",
    "Butterfree": "Butterfree's wings resemble Minoan frescoes. It started a psychedelic honey business using pollen from Crete's wildflowers that causes vivid dreams of ancient gods.",
    "Weedle": "Weedle pollinates wild thyme on Mount Olympus. A rogue Weedle once contaminated an entire feta production with its Poison Sting, creating the world's first glow-in-the-dark cheese.",
    "Kakuna": "Kakuna's form inspired Greek amphorae. Archaeologists were baffled when a 2,000-year-old vase suddenly hatched into a Beedrill during museum hours.",
    "Beedrill": "Beedrill guards sacred hives on Ikaria. It now leads a controversial 'Save the Bees' movement and has been known to chase tourists who swat insects.",
    "Pidgey": "Pidgey delivers messages between Meteora monasteries. One famously got lost in 1987 and delivered a monk's love letter to the wrong convent, sparking a minor scandal.",
    "Pidgeotto": "Pidgeotto scouts for lost hikers in Samaria Gorge. It charges €50 per rescue but gives discounts for Instagram influencers.",
    "Pidgeot": "Pidgeot races ferries between Santorini and Mykonos. A disgruntled captain once tried to catch it with a giant Poké Ball net, leading to a lawsuit.",
    "Rattata": "Rattata helps archaeologists discover hidden chambers. The most famous one found Plato's lost dialogue in 2003 but ate half the scroll before researchers could stop it.",
    "Raticate": "Raticate keeps granaries pest-free. A gourmet version has become a controversial delicacy in Thessaloniki, served with honey and thyme.",
    "Spearow": "Spearow's cry warns of storms in Peloponnese. Meteorologists tried to replace it with an app, but locals still trust the 'bird with the angry eyebrows' more.",
    "Fearow": "Fearow spots shipwrecks along Greece's coast. It runs a lucrative salvage operation but keeps 30% of whatever it finds.",
    "Ekans": "Ekans sunbathes on Delphi's theater stones. It starred in a viral video where it formed a perfect circle around the Oracle's stone that attracted New Age pilgrims.",
    "Arbok": "Arbok inspired serpent motifs on Asclepius' staff. A medical school in Athens employs one that can perfectly mimic ECG readings with its body waves.",
    "Pikachu": "Pikachu explores ruins while snacking on loukoumades! It powers all charging stations on the Athens Metro, though passengers complain about static shocks.",
    "Raichu": "Raichu powers Alexandroupoli's lighthouse during storms. During a blackout in 2019, it accidentally lit up so brightly that it was mistaken for a UFO.",
    "Sandshrew": "Sandshrew digs tunnels through Santorini's volcanic soil. Its underground Airbnb 'Cave Sweet Cave' has perfect ratings despite the occasional cave-ins.",
    "Sandslash": "Sandslash's spines inspired Spartan spear tips. It now runs a hedge-trimming service in Crete but has a habit of 'pruning' stone walls too.",
    "Nidoran♀": "Nidoran♀'s venom is used in ancient Greek medicines. Modern pharmacists use micro-doses in anti-aging creams that promise 'goddess-like radiance'.",
    "Nidorina": "Nidorina leads herds through Mount Parnassus' wildflowers. She headbutted a famous poet in 1987 who claimed it gave him creative inspiration.",
    "Nidoqueen": "Nidoqueen protects her young in Diros' caves. She recently blocked the entrance for 3 days protesting tourist flash photography near her nest.",
    "Nidoran♂": "Nidoran♂ polishes marble sculptures in Athens. The Acropolis Museum hired him full-time after he fixed a crack in Aphrodite's nose in 10 seconds.",
    "Nidorino": "Nidorino participates in Cretan wrestling matches. He was banned in 2010 for excessive horn usage but reinstated as a 'cultural tradition'.",
    "Nidoking": "Nidoking's frame inspired Minotaur myths. He plays the monster in Crete's labyrinth tourist attraction but takes smoke breaks that ruin the immersion.",
    "Clefairy": "Clefairy dances under the full moon at Artemis' Temple. TikTokers flock to record it, though many phones mysteriously malfunction during the dance.",
    "Clefable": "Clefable's powers were mistaken for oracles at Delphi. It now runs a psychic hotline that's 80% accurate but charges €5/minute.",
    "Vulpix": "Vulpix keeps warm near Santorini's volcanic springs. Instagrammers risk burns for selfies, leading to the hashtag #VulpixVictims.",
    "Ninetales": "Ninetales' nine tails represent the nine muses. An Athens museum hired one as a guide that points to exhibits with its tails.",
    "Jigglypuff": "Jigglytuff sings lullabies in Cretan tavernas. Its most famous incident put an entire wedding party to sleep for 18 hours mid-reception.",
    "Wigglytuff": "Wigglytuff's fur lines royal beds in Knossos Palace. Allergy sufferers protested this, leading to the 'Great Sneeze Debate' of 2003.",
    "Zubat": "Zubat navigates Melissani's labyrinthine caves. A famous cave diver got lost for 3 days following one that turned out to be leading him in circles.",
    "Golbat": "Golbat controls mosquitoes in Greek wetlands. It started charging local governments per mosquito eaten during the 2020 infestation crisis.",
    "Oddish": "Oddish grows rare herbs on Mount Pelion. A Michelin-starred chef uses its leaves in a €500 dish that allegedly makes you see nymphs.",
    "Gloom": "Gloom's pollen creates hypnotic effects at Dionysian festivals. Festival-goers complain it makes them dance uncontrollably to folk music.",
    "Vileplume": "Vileplume's flower inspired Minoan lily frescoes. It now models for botanical artists but causes pollen-induced sneezing fits.",
    "Paras": "Paras cultivates mushrooms in Zagori's forests. Its psychedelic varieties are illegally sold as 'Olympus Vision' to backpackers.",
    "Parasect": "Parasect's giant mushroom is a Macedonian delicacy. Health officials keep warning about side effects, but tourists love the 'trip without the flight'.",
    "Venonat": "Venonat's eyes glow in Alistrati's dark caves. Cave tours now include 'Venonat Disco Nights' with glow sticks and electronic music.",
    "Venomoth": "Venomoth's scales create iridescent Greek pottery glazes. A forgery scandal erupted when ancient vases started glowing under blacklight.",
    "Diglett": "Diglett tunnels between Peloponnese archaeological sites. Construction workers hate it because it keeps popping up in foundation pits.",
    "Dugtrio": "Dugtrio uncovered Mycenae through synchronized digging. They now offer team-building workshops that corporations pay thousands for.",
    "Meowth": "Meowth collects ancient coins from Zakynthos shipwrecks. It runs a shady eBay store selling 'authentic' drachmas that are mostly replicas.",
    "Persian": "Persian lounges at Athens' Grand Bretagne Hotel. It demands belly rubs from celebrities and once scratched a politician who refused.",
    "Psyduck": "Psyduck gets headaches from bouzouki music in Plaka. Earplugs shaped like its head are sold as souvenirs at music shops.",
    "Golduck": "Golduck swims through Pavlopetri's sunken city. Marine archaeologists use it to find artifacts, though it keeps hiding them for fun.",
    "Mankey": "Mankey steals olives from Kalamata groves. Farmers installed electric fences, but it just gets angrier and throws harder.",
    "Primeape": "Primeape participates in pomegranate throwing contests. It holds the record but was disqualified in 2022 for eating the targets.",
    "Growlithe": "Growlithe guards sheep flocks in Pindus mountains. It secretly lets wolves take one sheep per month 'to maintain ecological balance'.",
    "Arcanine": "Arcanine's speed inspired Cerberus legends. It now does emergency ambulance runs in remote villages, outpacing helicopters.",
    "Poliwag": "Poliwag cleans Thessaloniki's waterways. The mayor gave it a medal, but it lost it down a drain immediately.",
    "Poliwhirl": "Poliwhirl creates whirlpools in Corinth Canal. Boat captains hate it because it makes their GPS go haywire.",
    "Poliwrath": "Poliwrath protects swimmers at Navagio Beach. It rescued 15 tourists in 2020 but billed them for 'premium lifeguard services'.",
    "Abra": "Abra teleports between Parthenon columns. Security cameras only catch blurry images, fueling ghost stories.",
    "Kadabra": "Kadabra bends spoons during psychic readings. Athens street psychics hire it to impress tourists, paying in Greek coffee.",
    "Alakazam": "Alakazam solves equations at Aristotle University. Professors resent how it finishes exams in 2 minutes and naps for the rest.",
    "Machop": "Machop trains for stone lifting in Crete. It broke the record in 2019 but dropped the stone on the judge's foot.",
    "Machoke": "Machoke builds traditional stone houses in Mani. Its construction company slogan: 'If it doesn't hurt, you're not Machoke-ing hard enough!'",
    "Machamp": "Machamp wins Cretan stone-lifting competitions. Its secret? Four protein shakes daily made with Greek yogurt and honey.",
    "Bellsprout": "Bellsprout grows among carnivorous plants in Epirus. Botanists discovered it actually high-fives passing insects before eating them.",
    "Weepinbell": "Weepinbell catches insects in Prespa's wetlands. Birdwatchers complain it scares away rare species by burping loudly.",
    "Victreebel": "Victreebel inspired man-eating plant myths. A Thessaloniki restaurant serves soup in its leaves that 'tingles dangerously'.",
    "Tentacool": "Tentacool's sting is worse than Mediterranean jellyfish. Beach clubs sell 'Tentacool-proof' lotion that's just cheap sunscreen.",
    "Tentacruel": "Tentacruel guides ships near Cape Maleas. It demands offerings of calamari, or it creates whirlpools around stingy vessels.",
    "Geodude": "Geodude rolls down Meteora's hills polishing paths. Monastery monks use them as living roombas but complain about scratched floors.",
    "Graveler": "Graveler repairs Rhodes' ancient stone walls. It causes traffic jams by rolling across roads during rush hour.",
    "Golem": "Golem inspired Mycenae's cyclopean masonry. Modern engineers tried to hire it for the Athens Metro, but it kept curling into a ball.",
    "Ponyta": "Ponyta races across Thessaly's plains. Jockeys use special fireproof saddles, though many still get singed eyebrows.",
    "Rapidash": "Rapidash lights nighttime processions with its mane. A famous incident in 2015 set a float on fire during Easter celebrations.",
    "Slowpoke": "Slowpoke naps on Elafonissi's warm sands. Tourists mistake it for driftwood and accidentally sit on it daily.",
    "Slowbro": "Slowbro fishes for octopus in the Dodecanese. It once spent 3 days reeling one in that turned out to be a discarded tire.",
    "Magnemite": "Magnemite interferes with compasses near Hephaestus' Temple. Archaeologists use them to find buried metal artifacts.",
    "Magneton": "Magneton preserves ancient metal artifacts. A museum security system uses them to zap thieves with tiny lightning bolts.",
    "Farfetch'd": "Farfetch'd stirs giant pots of fasolada stew. Top chefs compete to hire it, but it only works for unlimited leeks.",
    "Doduo": "Doduo runs messages between Athens and Sparta. It claims it can beat the original marathon time but keeps getting distracted.",
    "Dodrio": "Dodrio watches over Nemea's vineyards. Its three heads argue constantly about grape ripeness, driving winemakers crazy.",
    "Seel": "Seel plays in waves at Vai Beach. It learned to balance palm fronds on its nose for tourist photos in exchange for fish.",
    "Dewgong": "Dewgong guides dolphins around Alonissos. Marine biologists discovered it teaches them synchronized swimming routines.",
    "Grimer": "Grimer cleans oil spills in the Saronic Gulf. Environmentalists protest that it just moves pollution to different beaches.",
    "Muk": "Muk fertilizes Kalamata olive groves. Gourmet oils from these trees cost €100/bottle but taste suspiciously like dirt.",
    "Shellder": "Shellder produces pearls for Minoan jewelry. Jewelers wait for its sneezes, which launch pearls like popcorn.",
    "Cloyster": "Cloyster protects coves along Mani's coast. It fires Icicle Spears at boats that come too close, puncturing hulls.",
    "Gastly": "Gastly haunts Knossos Palace at night. Guards report cold spots and the smell of sulfur, but it's just Gastly reheating moussaka.",
    "Haunter": "Haunter appears in mountain village ghost stories. A reality TV show spent €500,000 trying to film it but only captured fog.",
    "Gengar": "Gengar plays tricks at Mycenaean tombs. Its favorite prank is materializing behind tourists in group photos with a creepy grin.",
    "Onix": "Onix tunnels through Greek mountains creating paths. Hiking maps mark 'Onix Zones' where you might get knocked over by a speeding rock snake.",
    "Drowzee": "Drowzee eats dreams of tourists who overindulge in ouzo. Victims report nightmares of dancing plates and giant kebabs chasing them.",
    "Hypno": "Hypno's pendulum inspired ancient sundials. Street hypnotists use it for tourist shows but get sued for accidental time-loss.",
    "Krabby": "Krabby hides in Halkidiki's rock pools. Beachgoers scream when it pinches toes, thinking it's a giant sea monster.",
    "Kingler": "Kingler cracks sea urchins for gourmet dishes. Top restaurants serve 'Kingler-cracked uni' at triple the price.",
    "Voltorb": "Voltorb powers ancient Greek automatons in museums. Curators live in fear of it exploding during school tours.",
    "Electrode": "Electrode provides emergency power during island blackouts. Locals complain it makes their appliances run at double speed.",
    "Exeggcute": "Exeggcute rolls down hills like Easter eggs in Corfu. The 1998 incident where 200 rolled into a wedding reception remains legendary.",
    "Exeggutor": "Exeggutor shades ancient theaters in Epidaurus. Actors love performing under it except when coconuts drop mid-soliloquy.",
    "Cubone": "Cubone wears a skull from Mycenaean burial sites. Archaeologists tried to confiscate it but cried when Cubone looked sad.",
    "Marowak": "Marowak's bone club inspired Hercules' weapon. It teaches self-defense classes in Sparta with the motto: 'Bone up on safety!'",
    "Hitmonlee": "Hitmonlee teaches martial arts at the original Olympic site. Its 'Flying Kick Fitness' classes have waiting lists.",
    "Hitmonchan": "Hitmonchan spars with boxers in Thessaloniki gyms. It wears miniature boxing gloves knitted by local grandmothers.",
    "Lickitung": "Lickitung cleans ancient mosaics in Pella. Conservators complain it leaves everything sticky but germ-free.",
    "Koffing": "Koffing clears Athens' smog by absorbing pollution. Environmentalists worry what happens when it explodes from overeating fumes.",
    "Weezing": "Weezing filters factory emissions in Thessaloniki. Industrialists call it 'eco-friendly' but workers wear gas masks nearby.",
    "Rhyhorn": "Rhyhorn charges through Thrace's mountains. Farmers use it to plow fields but must replace fences weekly.",
    "Rhydon": "Rhydon's drill horn uncovers archaeological sites. It accidentally destroyed a Roman villa in 2010 while 'helping'.",
    "Chansey": "Chansey helps nurses in Greek hospitals. Its eggs cure hangovers so effectively that party islands want to ban it.",
    "Tangela": "Tangela's vines make traditional Greek baskets. Weavers complain it tickles them while working and ruins patterns.",
    "Kangaskhan": "Kangaskhan protects its young in Crete's gorges. Tourist drones keep filming its pouch, leading to aerial chases.",
    "Horsea": "Horsea creates miniature whirlpools in coves. Yachties pay it to mix their cocktails with its water jets.",
    "Seadra": "Seadra's spines modeled ancient sea monsters. Fishermen tell tales of it piercing nets to steal entire catches.",
    "Goldeen": "Goldeen dances in Athens' National Garden fountains. Visitors throw coins, not knowing it hoards them in a secret pond vault.",
    "Seaking": "Seaking's horn pierces fishing nets in protest. An activist group hired it to sabotage trawlers illegally overfishing.",
    "Staryu": "Staryu washes up during meteor showers. Astronomers pay beachcombers €10 per Staryu for 'cosmic research'.",
    "Starmie": "Starmie's core glows like the Star of Vergina. It's banned from museums after trying to 'replace' exhibits in display cases.",
    "Mr. Mime": "Mr. Mime performs in Plaka's street theaters. Its invisible walls trap tourists until they pay for 'mime liberation'.",
    "Scyther": "Scyther trims olive trees with razor blades. Farmers love its precision but must hide their scarecrows - it decapitates them.",
    "Jynx": "Jynx's dance inspired Greek tragic masks. A theater banned it for 'disturbing realism' after audience members froze in terror.",
    "Electabuzz": "Electabuzz absorbs lightning on Mount Olympus. Meteorologists installed a camera on its horn for storm forecasts.",
    "Magmar": "Magmar heats thermal springs on Milos. Tourism boomed after it created a new hot spring overnight by sneezing lava.",
    "Pinsir": "Pinsir cracks walnuts in Greek bakeries. It moonlights as a nutcracker in Christmas markets but terrifies children.",
    "Tauros": "Tauros participates in bull-leaping ceremonies. Animal rights activists protest, but it winks at performers before charging.",
    "Magikarp": "Magikarp is a delicacy with Santorini tomatoes. Top chefs serve it as 'Explosive Sashimi' - it sometimes evolves mid-meal.",
    "Gyarados": "Gyarados patrols Corinth Canal ensuring safe passage. Ship captains pay tolls in fish, or it creates artificial storms.",
    "Lapras": "Lapras offers rides between Cyclades islands. Its 'Shell Express' service is cheaper than ferries but slower and soggier.",
    "Ditto": "Ditto transforms into famous Greek statues in museums. Guards have nightmares about the 'Night of a Thousand Aphrodites' incident.",
    "Eevee": "Eevee changes evolution based on Greek islands visited: Vaporeon in Hydra, Jolteon in Mykonos, Flareon in Santorini. Tour operators offer 'Eeveelution Packages'.",
    "Vaporeon": "Vaporeon plays in Edessa's waterfalls. It creates rainbow mists so perfect, they're trademarked for tourism ads.",
    "Jolteon": "Jolteon stores Santorini's lightning electricity. It powers the entire island for 3 minutes after major storms.",
    "Flareon": "Flareon keeps warm near Nisyros' volcanic vents. Scientists study its fur as a model for heat-resistant fabrics.",
    "Porygon": "Porygon appears in digital reconstructions of ancient sites. Hackers use it to insert glitchy memes into virtual tours.",
    "Omanyte": "Omanyte fossils inspired Kraken legends. A live one surfaced in 2018, ate a fishing boat, and was nicknamed 'Ouzo Kraken'.",
    "Omastar": "Omastar's shell patterns appear on ancient coins. Numismatists found modern replicas made by Omastar pressing shells into clay.",
    "Kabuto": "Kabuto fossils are displayed in the Natural History Museum. School tours love them until Kabutops skeletons start moving at night.",
    "Kabutops": "Kabutops cuts fishing nets in the Aegean. Fishermen retaliated with electrified nets, causing an 'aquatic arms race'.",
    "Aerodactyl": "Aerodactyl fossils were mistaken for griffin remains. A theme park tried cloning them in 2015 - the resulting chaos closed the park.",
    "Snorlax": "Snorlax naps on the Acropolis' marble steps. Guards tried moving it with cranes, but it just rolled back like a fuzzy boulder.",
    "Articuno": "Articuno keeps Mount Olympus cool during summer. Ski resorts pay it to make artificial snow out of season.",
    "Zapdos": "Zapdos provides lightning shows over Poseidon's Temple. Photographers wait for storms to capture 'Electric God' shots.",
    "Moltres": "Legend says Moltres gifted the eternal flame to Prometheus. Olympic officials keep trying to borrow it but fear fire code violations.",
    "Dratini": "Dratini swims in Lake Plastira's depths. Locals tell children it's the 'Loch Ness Monster's Greek cousin'.",
    "Dragonair": "Dragonair's appearance heralds good fortune in ports. Fishermen throw their best catch to it for blessings - or to avoid anger.",
    "Dragonite": "Dragonite calms seas for Mykonos fishermen. It charges one fish per calm voyage, payable upfront.",
    "Mewtwo": "Mewtwo meditates at the Oracle of Delphi. It claims to receive visions but mostly complains about tourist noise.",
    "Mew": "Mew inspired the Phoenix myth. It was spotted during the 2008 Athens riots, turning tear gas into harmless bubbles.",
}

# Fun facts for all Gen 2 Pokémon
GEN_2_FACTS = {
    "Chikorita": "Chikorita grazes in the fields around the Temple of Olympian Zeus. It once got tangled in an American tourist's selfie stick and became a meme as 'Leafy Trouble'.",
    "Bayleef": "Bayleef's spicy leaves flavor tsipouro liquor in Thessaly. Distilleries guard their Bayleef herds fiercely - industrial espionage involves leaf-napping.",
    "Meganium": "Meganium's breath revives dead olive groves. Farmers call it 'The Resurrector' and leave offerings of honey at stone circles.",
    "Cyndaquil": "Cyndaquil keeps bakeries warm during winter in Metsovo. Famous for accidentally burning down a bakery in 2015 while proving its 'passion' for bread.",
    "Quilava": "Quilava clears snow from mountain roads with controlled burns. The fire department constantly reprimands it for 'overenthusiastic' melting.",
    "Typhlosion": "Typhlosion maintains volcanic activity on Nisyros. Geologists worry it's showing off for tourists with unnecessary eruptions.",
    "Totodile": "Totodile plays in the Alpheios River near Olympia. It chews on ancient marble fragments, giving archaeologists nightmares.",
    "Croconaw": "Croconaw guards river crossings in the Peloponnese. It demands a 'tooth fee' of candy or shiny objects from travelers.",
    "Feraligatr": "Feraligatr lurks in the Acheloos River. Kayakers tell tales of being chased by 'giant green logs with teeth'.",
    "Sentret": "Sentret watches over village squares in Zagori. It started a neighborhood watch program and reports crimes by tapping windows.",
    "Furret": "Furret races through Venetian alleyways in Nafplio. Local cats formed an anti-Furret alliance after it stole their napping spots.",
    "Hoothoot": "Hoothoot nests in the clock tower of Athens. Its perfectly timed hoots synchronize with the chimes, confusing tourists about time zones.",
    "Noctowl": "Noctowl guides night tours at Delphi. It uses Hypnosis to make tourists imagine ancient battles - several sued for 'unlicensed time travel'.",
    "Ledyba": "Ledyba forms constellations on vineyard nets in Nemea. Winemakers say more Ledyba mean sweeter grapes but also more sticky fingers.",
    "Ledian": "Ledian's spots glow like stars in Arcadia. A UFO sighting in 2003 turned out to be a swarm doing synchronized flying.",
    "Spinarak": "Spinarak weaves silk barriers around archaeological sites. Conservators appreciate it until they walk face-first into invisible webs.",
    "Ariados": "Ariados creates giant webs between Meteora pillars. Base jumpers accidentally use them as safety nets, with mixed results.",
    "Crobat": "Crobat patrols Athens' metro tunnels at night. Commuters complain about 'swooping shadows' but appreciate the mosquito control.",
    "Chinchou": "Chinchou lights underwater caves in Kefalonia. Scuba tours feature 'Chinchou disco dives' with glow sticks and techno music.",
    "Lanturn": "Lanturn illuminates deep-sea fishing boats. Fishermen call it 'humanity's bulb' but warn not to touch - its shocks cure stubborn hiccups.",
    "Pichu": "Pichu plays with feral cats in Plaka. Videos of it accidentally zapping cats have millions of views - the cats keep coming back for more.",
    "Cleffa": "Cleffa dances under shooting stars on Mount Parnassus. Astronomers use its movements to predict meteor showers with 95% accuracy.",
    "Igglybuff": "Igglybuff sings nursery rhymes in Athenian kindergartens. It once caused a city-wide naptime when its Sing amplified over PA systems.",
    "Togepi": "Togepi brings luck to newlyweds on Rhodes. Hotels offer 'Togepi Blessing Packages' including shell-polishing and photo ops.",
    "Togetic": "Togetic guards the Bridge of Arta. Legend says it will collapse if Togetic ever stops flying around it - so locals feed it honey cakes.",
    "Natu": "Natu hops among the Caryatids on the Acropolis. It claims to see the future but only shares prophecies about snack times.",
    "Xatu": "Xatu stands motionless at Thermopylae. Tourists mistake it for a statue until it suddenly teleports away screaming about 'doomed timelines'.",
    "Mareep": "Mareep grazes in the electric wind farms of Evia. Its wool stores static - shearers wear rubber suits to avoid shocking haircuts.",
    "Flaaffy": "Flaaffy powers remote villages in the Mani Peninsula. Locals knit its wool into shockproof sweaters that glow during storms.",
    "Ampharos": "Ampharos serves as living lighthouses on Lesbos. It once overloaded during a storm and lit the entire island like a Christmas tree.",
    "Bellossom": "Bellossom dances in Thessaloniki's flower markets. Florists complain it hypnotizes customers into buying more bouquets.",
    "Marill": "Marill floats down rivers in inflatable doughnuts. A viral video showed it squeaking the Greek anthem on a kazoo.",
    "Azumarill": "Azumarill rescues flood victims in Macedonia. It uses its belly as a raft but demands belly rubs as payment.",
    "Sudowoodo": "Sudowoodo poses as olive trees in Pelion forests. Woodcutters tell tales of 'screaming lumber' when axes hit them.",
    "Politoed": "Politoed leads frog choruses in Prespa's wetlands. Its conducting skills earned it a guest spot with the Athens State Orchestra.",
    "Hoppip": "Hoppip drifts over Santorini caldera. Paragliders sometimes catch them for 'lucky lifts' - they pop if squeezed too hard.",
    "Skiploom": "Skiploom predicts weather on Karpathos. Locals say if it flies high, expect sun; if low, rain; if spinning, tornado (it's usually just dizzy).",
    "Jumpluff": "Jumpluff seeds create temporary meadows on Mykonos. The tourism board hates how it covers luxury pools in fluffy pollen.",
    "Aipom": "Aipom steals sunglasses in Corfu beach clubs. It wears them all on its tail like a bizarre accessory rack.",
    "Sunkern": "Sunkern rolls through sunflower fields in Serres. Farmers installed tiny ramps for them, creating 'Sunkern skate parks'.",
    "Sunflora": "Sunflora tracks sunlight for solar farms in Crete. Engineers love its efficiency except when it does sun salutations during peak hours.",
    "Yanma": "Yanma hunts mosquitoes over Lake Kerkini. Birdwatchers initially mistook it for a dragonfly until it used Hypnosis on binoculars.",
    "Wooper": "Wooper waddles through the Nestos River mudflats. Its mucus is used in expensive face creams that promise 'amphibian radiance'.",
    "Quagsire": "Quagsire digs irrigation channels in Thessaly. It gets distracted by shiny rocks and often digs in the wrong direction.",
    "Espeon": "Espeon predicts lottery numbers in Athens. It's banned from kiosks after winning too often - now it communicates through dreams.",
    "Umbreon": "Umbreon glows in moonlit Dionysian festivals. Club owners hire it as a living disco ball but warn about 'mystery bruises' later.",
    "Murkrow": "Murkrow steals shiny coins from the Trevi Fountain replica in Athens. It hoards them in the National Garden's oldest tree.",
    "Slowking": "Slowking solves puzzles in escape rooms in Thessaloniki. Owners hate it because it either solves instantly or stares blankly for hours.",
    "Misdreavus": "Misdreavus haunts the Mycenaean tombs at night. It imitates tourist voices, luring people into dark corridors for 'spooky selfies'.",
    "Unown": "Unown forms cryptic messages on Delos' ancient walls. Archaeologists debate if it's profound or just spelling 'OUZO' repeatedly.",
    "Wobbuffet": "Wobbuffet appears unexpectedly in selfies at the Acropolis. Its wide grin photobombs over 2000 Instagram posts daily.",
    "Girafarig": "Girafarig reaches high olives in Kalamata groves. Its tail sometimes argues with farmers about which olives are ripe.",
    "Pineco": "Pineco dangles from pine trees in Parnitha National Park. Hikers wear helmets after the 'Great Pinecone Bombing' of 2019.",
    "Forretress": "Forretress protects monasteries in Meteora. Monks use them as living bells - tapping shells signals prayer time.",
    "Dunsparce": "Dunsparce digs through archaeological sites at Pella. It tunnels into mosaics, causing conservators to chase it with nets.",
    "Gligar": "Gligar glides between Santorini cliffs. Paragliding companies offer 'Gligar tandem flights' - it drops passengers at random spots.",
    "Steelix": "Steelix tunnels under the Athens Metro. Construction halted for 6 months when one surfaced beneath Syntagma Square screaming.",
    "Snubbull": "Snubbull guards jewelry stores in Athens' Kolonaki. Its intimidating scowl is undercut by a pink bow tie uniform.",
    "Granbull": "Granbull pulls carts in Hydra's car-free streets. Donkeys unionized against it for 'stealing jobs with brute strength'.",
    "Qwilfish": "Qwilfish inflates in the Amvrakikos Gulf. Fishermen use it as a buoy but warn: 'Never pop a Qwilfish - the stench lasts weeks'.",
    "Scizor": "Scizor trims grapevines in Naoussa vineyards. Its blades are calibrated to cut exactly one millimeter - winemakers call it 'The Surgeon'.",
    "Shuckle": "Shuckle ferments berry wine in mountain caves. Bootleggers sell 'Shuckle Juice' at festivals - one sip causes week-long naps.",
    "Heracross": "Heracross lifts fishing boats in Symi harbor. It charges €50 per lift but drops them if not paid promptly.",
    "Sneasel": "Sneasel steals silver from Byzantine churches. Police set honey traps with fake communion plates - it took the honey and left glitter.",
    "Teddiursa": "Teddiursa raids honey farms on Mount Olympus. Beekeepers installed electric fences, but it just high-fives them for fun.",
    "Ursaring": "Ursaring hibernates in Pindos National Park. Rangers mark its den with 'Bearxit' signs warning tourists not to disturb.",
    "Slugma": "Slugma heats outdoor pools in Loutraki. Hotel guests love it until they step on one and get 'lava foot'.",
    "Magcargo": "Magcargo melts snow on Epiros roads. Road crews follow it with salt trucks yelling 'Faster, lava snail!'",
    "Swinub": "Swinub roots for truffles in Grevena forests. Truffle hunters compete to hire them - they accept payment in acorns and belly rubs.",
    "Piloswine": "Piloswine clears ski slopes on Mount Vermio. It uses Icy Wind to make artificial snow but sometimes buries lift operators.",
    "Corsola": "Corsola regenerates damaged reefs in Zakynthos. Marine biologists discovered its horns filter microplastics - slowly.",
    "Remoraid": "Remoraid hitches rides on ferry propellers. Engineers find them clogging engines with messages like 'Wish you were here' scratched on hulls.",
    "Octillery": "Octillery inks ancient shipwrecks in the Aegean. Underwater photographers pay it not to ruin shots during dives.",
    "Delibird": "Delibird delivers Christmas gifts in Thessaloniki. Its bag has endless space but delivers randomly - you might get coal or diamonds.",
    "Mantine": "Mantine glides past Navagio Beach. Surfers ride them illegally, calling it 'mantisurfing' - lifeguards issue €500 fines.",
    "Skarmory": "Skarmory nests on wind turbines in Evia. Technicians wear chainmail suits to avoid cuts during maintenance.",
    "Houndour": "Houndour herds sheep in the Pindus Mountains. Its howls sound like bouzouki music - shepherds dance while working.",
    "Houndoom": "Houndoom guards the gates of Hades in mythology tours. Actors hire it for realism but warn about 'unscripted terror'.",
    "Kingdra": "Kingdra creates waterspouts near Alonissos. Sailors throw offerings of squid to avoid being 'dragon-swirled'.",
    "Phanpy": "Phanpy sprays tourists at the Palace of Knossos fountains. Guards installed 'Phanpy-proof' barriers - it sprays through them.",
    "Donphan": "Donphan rolls through Thessaloniki's White Tower square. It's featured on the city's 'Wildlife Hazard' signs beside pigeons.",
    "Porygon2": "Porygon2 hacks ATM machines in Athens. Police can't arrest it because 'digital Pokémon aren't covered by Greek law'.",
    "Stantler": "Stantler's antlers create optical illusions in Meteora. Several tourists walked off cliffs chasing 'psychedelic visions'.",
    "Smeargle": "Smeargle paints graffiti in Exarchia, Athens. Its abstract work sells for thousands despite being drawn with tail-slime.",
    "Tyrogue": "Tyrogue trains at the original Olympic wrestling pit. It challenges toddlers to matches and always lets them win.",
    "Hitmontop": "Hitmontop breakdances in Plaka's street performances. Crowds throw euros but duck when it starts spinning kicks.",
    "Smoochum": "Smoochum kisses babies at baptisms in Crete. Parents pay extra for 'divine puckers' that supposedly bring intelligence.",
    "Elekid": "Elekid powers bumper cars at the Allou Fun Park. It gets overexcited and zaps riders, leaving their hair standing on end.",
    "Magby": "Magby lights grills at beach tavernas in Paros. Chefs love its consistency except when it sneezes and chars the seafood.",
    "Miltank": "Miltank produces yogurt milk in Metsovo. Its 'volcanic grass diet' makes the yogurt glow slightly - and taste like sulfur.",
    "Blissey": "Blissey works in Greek hospital maternity wards. Newborns given its eggs never cry but smile creepily at 3 AM.",
    "Raikou": "Raikou races thunderstorms over Mount Olympus. Lightning photographers risk electrocution for the perfect 'storm tiger' shot.",
    "Entei": "Entei's roar triggers volcanic activity on Santorini. Geologists monitor it with seismographs labeled 'Big Kitty'.",
    "Suicune": "Suicune purifies Lake Trichonida. Environmentalists found it removes microplastics but leaves a faint blue glitter.",
    "Larvitar": "Larvitar eats rocks at the Temple of Poseidon. Archaeologists found half the columns nibbled - it claims it's 'restoration'.",
    "Pupitar": "Pupitar rolls down hills in Delphi. Tour buses swerve to avoid 'armored beach balls' - rental companies charge damage fees.",
    "Tyranitar": "Tyranitar basks in the Lavrio mining region. Miners tell legends of it eating entire bulldozers for snacks.",
    "Lugia": "Lugia sleeps in the deepest trench near Crete. Naval sonar sometimes wakes it, causing freak waves that sink fishing boats.",
    "Ho-Oh": "Ho-Oh's rainbow feathers appear over Rhodes after storms. Tourism ads promise 'guaranteed Ho-Oh sightings or your drachma back'.",
    "Celebi": "Celebi tends ancient olive groves in Crete. Farmers leave offerings hoping it will time-travel their trees to avoid bad harvests.",
}

# Combined dictionary for all specific Pokémon facts
ALL_SPECIFIC_FACTS = {**ORIGINAL_151_FACTS, **GEN_2_FACTS}

# --- Name normalization so variants share the same fun fact ---
# Examples handled:
# 'Lugia EX', 'Lugia ex', 'M Charizard-EX', 'Charizard VSTAR', 'Charizard VMAX',
# 'Radiant Greninja', 'Shining Mew', 'Galarian Moltres V', 'Lugia & Ho-Oh GX' (keeps first)
_VARIANT_SUFFIX_RE = re.compile(
    r"\s*(?:-?\s*(?:ex|gx|v(?:max|star|\s*-?union)?|prime|break|legend))\b.*$",
    flags=re.IGNORECASE,
)
_VARIANT_PREFIX_RE = re.compile(
    r"^(?:mega|m|radiant|shining|primal|alolan|galarian|hisuian|paldean|shadow|dark|light)\s+",
    flags=re.IGNORECASE,
)

def _base_species_name(name: str) -> str:
    if not name:
        return ""
    s = str(name).strip()

    # For tag-team / multi-Pokémon names, keep the first species
    s = re.split(r"\s*(?:&|and|/|\+)\s*", s, maxsplit=1)[0]

    # Remove suffix mechanics (EX/GX/V/VMAX/VSTAR/V-UNION/etc.)
    s = _VARIANT_SUFFIX_RE.sub("", s)

    # Remove leading descriptors (Mega, Radiant, Shining, regional forms, etc.)
    s = _VARIANT_PREFIX_RE.sub("", s)

    # Collapse whitespace
    return re.sub(r"\s+", " ", s).strip()

# Enhanced dynamic templates for other Pokémon
DYNAMIC_TEMPLATES = [
    "Legend says {pokemon} inspired the myth of {mythical_creature}. Recently, it was seen {activity} in {greek_location}, causing {funny_consequence}!",
    "{pokemon} loves {activity} in {greek_location}. Locals have started a festival called 'The {pokemon} Celebration' featuring {greek_food} and {greek_dance}.",
    "You can find {pokemon} enjoying {greek_food} at tavernas in {greek_island}. Rumor says it once {bizarre_incident} during a cooking show!",
    "{pokemon} participates in {greek_festival} annually. Last year, it {funny_achievement} and now appears on souvenir {souvenir_item}.",
    "During visits to {greek_landmark}, tourists report {pokemon} {activity}. Scientists say it's {scientific_explanation}, but locals know it's just {humorous_truth}.",
    "{pokemon} learned {greek_dance} from YouTube. It now performs in {greek_location} squares, charging €{random_number} for photos with its {funny_accessory}.",
    "{pokemon}'s design was inspired by {greek_mythology_figure}. A museum tried to display it as 'living art' until it {funny_museum_incident}.",
    "{pokemon} helps with {greek_activity} in rural villages. Its unique technique involves {unexpected_method} that both impresses and terrifies locals.",
    "In Greek waters, {pokemon} {activity} near {greek_island}. Fishermen tell tales of it {mythical_comparison} while stealing {stolen_item}.",
    "{pokemon} collects {greek_natural_resource} from {greek_region} mountains. The resulting {product} sells for €{expensive_price} at boutique stores in Mykonos.",
    "Local legend says {pokemon} brings luck to {greek_tradition} celebrations. Proof? When it attended, {miraculous_event} happened!",
    "{pokemon} appears on {greek_product} packaging after {funny_marketing_story}. Consumers report {strange_side_effect} after consumption.",
    "{pokemon} starred in the Greek dub of {famous_movie}. Critics praised its {acting_skill} though it kept {movie_mishap} during takes.",
    "A {pokemon} was elected mayor of {greek_village} in 2022. Its first decree: mandatory {silly_policy} that actually {policy_outcome}."
]

# Expanded Greek elements
GREEK_ELEMENTS = {
    "mythical_creature": ["the Minotaur", "the Cyclops", "the Sphinx", "the Hydra", "Cerberus", "Pegasus"],
    "activity": ["swimming in crystal clear waters", "dancing traditional dances", "exploring ancient ruins", 
                "sunbathing on sandy beaches", "climbing mountains", "stealing souvlaki", "photobombing tourists"],
    "greek_location": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Rhodes Town", "Nafplio", "Chania"],
    "greek_food": ["moussaka", "souvlaki", "baklava", "tzatziki", "feta cheese", "olives", "loukoumades", "spanakopita"],
    "greek_festival": ["the Carnival of Patras", "Easter celebrations", "the Athens Festival", 
                      "the Wine Festival", "Olympic Games ceremonies", "the Sardine Festival"],
    "greek_landmark": ["the Parthenon", "Delphi", "Meteora", "Knossos Palace", "the Acropolis", "Olympia", "Mycenae"],
    "greek_dance": ["sirtaki", "kalamatianos", "tsamiko", "zeibekiko", "hasapiko", "ballos", "syrtos"],
    "greek_mythology_figure": ["Zeus", "Athena", "Poseidon", "Apollo", "Artemis", "Hermes", "Dionysus", "Hades"],
    "greek_activity": ["olive harvesting", "grape stomping", "fishing", "sheep herding", "beekeeping", "yoga retreats"],
    "greek_island": ["Santorini", "Mykonos", "Crete", "Corfu", "Rhodes", "Zakynthos", "Paros", "Naxos"],
    "greek_natural_resource": ["olives", "grapes", "honey", "herbs", "marble", "sea salt", "volcanic ash"],
    "greek_region": ["Macedonia", "Peloponnese", "Epirus", "Thessaly", "Central Greece", "Thrace", "Aegean Islands"],
    "greek_tradition": ["Easter", "name day celebrations", "weddings", "baptisms", "Greek Independence Day", "Clean Monday"],
    "greek_color_source": ["blue domes of Santorini", "whitewashed buildings", "Aegean Sea waters", 
                          "Greek flag colors", "Mediterranean sunset hues", "volcanic rock formations"],
    "funny_consequence": ["confused archaeologists", "a viral TikTok trend", "a new law being passed", "all the cats following it"],
    "bizarre_incident": ["ate the judges' scorecards", "set the kitchen on fire", "tried to pay with seashells", "evolved mid-recipe"],
    "funny_achievement": ["won the cheese-rolling contest", "flirted with the mayor", "created a new dance craze", "ate all the offerings"],
    "souvenir_item": ["t-shirts", "mugs", "fridge magnets", "shot glasses"],
    "scientific_explanation": "tectonic energy convergence",
    "humorous_truth": "showing off for treats",
    "random_number": ["2", "5", "10", "20", "50"],
    "funny_accessory": ["party hat", "gold chain", "miniature column", "feta cheese necklace"],
    "funny_museum_incident": ["ate a priceless artifact", "posed as a statue that winked", "led a conga line through exhibits", "sold tickets to itself"],
    "unexpected_method": ["singing off-key", "using psychic powers", "setting things on fire", "digging holes"],
    "mythical_comparison": ["summoning Poseidon", "creating whirlpools", "talking to dolphins", "riding seahorses"],
    "stolen_item": ["fishing nets", "anchors", "sunglasses", "picnic baskets"],
    "expensive_price": ["50", "100", "250", "500"],
    "miraculous_event": ["it rained chocolate", "everyone won the lottery", "a broken statue repaired itself", "the wine never ran out"],
    "greek_product": ["ouzo bottles", "coffee packages", "olive oil tins", "yogurt containers"],
    "funny_marketing_story": ["crashing a commercial shoot", "becoming a meme", "suing for likeness rights", "demanding royalties in fish"],
    "strange_side_effect": ["temporary levitation", "Greek language fluency", "uncontrollable dancing", "seeing ancient gods"],
    "famous_movie": ["Zorba the Greek", "Mamma Mia", "Clash of the Titans", "My Big Fat Greek Wedding"],
    "acting_skill": ["emotional range", "comedic timing", "improvisation", "method acting"],
    "movie_mishap": ["eating the props", "falling asleep", "accidentally evolving", "setting the set on fire"],
    "greek_village": ["Oia", "Fira", "Lindos", "Monemvasia"],
    "silly_policy": ["daily nap time", "free ouzo Fridays", "mandatory plate smashing", "sirtaki-only exercise hours"],
    "policy_outcome": ["improved tourism", "caused a riot", "made international news", "inspired a Netflix documentary"]
}

def get_greek_fun_fact(pokemon_name):
    """Return a Greek-themed fun fact using the base species name.
    Ensures variants like 'Lugia EX', 'Charizard VSTAR', 'Radiant Greninja'
    all resolve to the same fun fact as 'Lugia', 'Charizard', 'Greninja'.
    """
    base = _base_species_name(pokemon_name)

    # If we have a specific fact for the base species, use it
    if base in ALL_SPECIFIC_FACTS:
        return ALL_SPECIFIC_FACTS[base]

    # Otherwise, generate a dynamic fact (labelled with the base name)
    template = random.choice(DYNAMIC_TEMPLATES)

    for key, choices in GREEK_ELEMENTS.items():
        placeholder = f"{{{key}}}"
        if placeholder in template:
            template = template.replace(placeholder, random.choice(choices))

    return template.format(pokemon=base or pokemon_name)
